spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://kandariaman24_db_user:rXXLKSZM9LoGpN4j@cluster0.zygj8kb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: userdb
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: embarkx
#    password: embarkx
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082